# -*- coding: utf-8 -*-
"""Day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1jzEXsgpevQsEIwt1Pdwr5caVL_FxhH
"""

#Basic
age = 25
price = 19.98
name = "Amrit"
is_student = True

print(age,price,name,is_student)

#Loop
age= int(input("Enter age : "))
if age >= 18:
  print("Welcome !")
else:
  print("Sorry , Too Young")

#list create
Scores = [85,45,32,54,64]

#aescending order
first = Scores[0]
last = Scores[-1]

#slicing
top_3 = Scores[0:3]

print(first,last,top_3)

Scores = [85,45,32,54,64,89,21,90]

top_3 = Scores[-3:]
middle = Scores[3:7]
every_other = Scores[::2]
rev_score = Scores[::-1]

first_8 = Scores[:8]
pos_3= Scores[4:]
rev_score = Scores[::-1]

print(first_8, pos_3  , rev_score)

#Create Dict., Student Database

my_profile={
    "name":"Amrit",
    "age": 21,
    "skills": ["Python","Data analytics"],
    "scores":{"math":95, "coding":98}
}



#add skill

my_profile["skills"].append("ML")


#update score
my_profile["scores"]["coding"]=99



print(my_profile.get('age'))

import math
math.sqrt(16)
math.pi

import random
random.randint(1,10)
random.choice([1,2,3])

import random
name = ["Amol","Rishu","Amrit","stu_1","stu_2"]
for i in range(0,5):
  students={
      "name": random.choice(name),
      "age":random.randint(18,25),
      "score": random.randint(0,100)
      }
print(students)

from google.colab import drive
drive.mount('/content/drive')

a,b,c = [1,2,3]
print(f"a : {a}, b:{b}, c: {c}")

a,*b,c = [1,2,3,4,5,7,8]
print(f"a : {a}, b:{b}, c: {c}")

_,_,c = [1,2,3]
print(f"c: {c}")

data = ("Alice",(25, "Engineer"))
name, *profession = data
print(name)
print(age)
print(profession)

def print_names(*names):
  for name in names:
    print(name)
print_names("Alice","Bob","Charlie","Amrit","Amol")

l1=[1,2,3]
l2=[4,5,6]
combined = [*l1,*l2]
print(*l1)
print(f"Combined List: {combined}\n")

#concatenation


my_profile1={
    "name":"Amrit",
    "age": 21,
    "skills": ["Python","Data analytics"],
    "scores":{"math":95, "coding":98}
}

my_profile2={
    "name":"Amol",
    "age": 23,
    "skills": ["C","Data analytics"],
    "scores":{"math":87, "coding":68}
}
combined_2 = {**my_profile1,**my_profile2}
print(f"Combined List: {combined_2}\n")

l1=[1,2,3,4]
l2=l1.copy()

l1.append(5)
print(l1)
print(l2)